#!/bin/sh
while true; do
	sleep 12
	date="$(tail -1 $HOME/logs/latest.log | grep -oP '(?<=\[).*?(?=\])' | head -1 | date -f - +%s)"
	if [ "$(env printf '\xFE' | nc -w 5 localhost 25565 | wc -m)" -eq 1 ] ||
		[ "$(( $(date +%s) - ${date:=$(date +%s)} ))" -gt 180 ]; then
		if [ "$(tail -20 $HOME/logs/latest.log | grep -c 'ERROR]: Requested chunk')" -eq 1 ]; then
			rm -rf $HOME/worlds/
		fi
		pkill -9 java
	fi
done
