#!/bin/sh
export AUTOSSH_POLL=30
autossh -M 25564 -i ~/.ssh/remote -o StrictHostKeyChecking=no -o ExitOnForwardFailure=yes -o StreamLocalBindUnlink=yes -c aes128-ctr -C -S none -N -T -R 25565:localhost:25565 remote@play.kaboom.pw
