#!/bin/sh
while true; do
	cd $HOME/plugins/FastAsyncWorldEdit/schematics/
	if [ "$(git add $(git ls-files -o) -v)" ]; then
		git -c user.name='kaboom' -c user.email='kaboom.pw' commit -m "Add new schematics"
		git push
	fi
	sleep 1
done
